### ISSUE TITLE
Neuron_tasker Pas de telephone qui sonne ??

### ISSUE THREAD

**Issue by tet102** [kalliope-project/kalliope_neuron_tasker#1]
Hello, I just installed kalliope_neuron_tasker.
brain: find_phone ok / as an example.
I put my google API key.
message "lost".
Tasker installed on Tel with Tasks: Start_ring then Music_stop.
as in example.
profiles: Autoremote lost called Start Ring and display unlocked enabled
Kalliope understands well order lays sysnapse "find_phone".
Then said to me: I'm ringing the phone ...
nothing is happening.
Have an idea please, thank you for your help. 
Thanks
C'est corrigé (c'est en anglais) ...

**Comment by Sispheor** [comment]
@tet102 si tu peux mettre tes issues en anglais la prochaine fois, merci. cela peut aider d'autre personne.

Ensuite, API key google? Qu'est ce que Google vient faire la?

**Comment by tet102** [comment]
Hi Nicolas,
Sorry I don't read very well.
Ok. I verify  and It's written in the Doc : API key. Can be found in your personal URL given by the app.
Sorry, i just see it when i start Autoremote. it's written 
Go here to Remote control tasker
https://goo.gl/v......
And below its written: This is your personnal URL.Touch to share.
What can i do after ? I don't fin any key...
Thanks

**Comment by Sispheor** [comment]
Click on the link given by autoremote, this will redirect you to an URL like autoremotejoamgcd.appspot.com. Your key is in the URL. key=<my_key>.

**Comment by tet102** [comment]
Ok I just found it like you
Steps to get your personal Key:
Go to your personal URL
After the page has finished loading look in your URL. It will look something like http://autoremotejoaomgcd.appspot.com/?key=MY_KEY
Instead of MY_KEY, your key will be there. Copy your key with Control+C and paste it where needed with Control+V
I try this. thanks

**Comment by tet102** [comment]
Oh Yeah... I understand
key: "MY_VERY_LONG_KEY"
Thank you for you help. 
It works.... thanks a lot. lot lot lot lot....
